# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kostki-cicd

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodejs-microservices/packages/website/**'
      - '.github/workflows/main_kostki-cicd.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd nodejs-microservices
          npm install
          cd packages/website
          npm run build --if-present
#          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: nodejs-microservices/packages/website

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEA8D03A618C46208A1D51666D764D40 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E595AF5D62B4D5F9E130382F6DEC942 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FC77BAEE5C341C58C14C0A5A5BF779C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kostki-cicd'
          slot-name: 'Production'
          package: dist
          
