name: Trigger auto deployment for ryba-dice-cicd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'nodejs-microservices/packages/dice-api/**'
    - '.github/workflows/ryba-dice-cicd-AutoDeployTrigger-dd0a9961-8c64-45ba-a8e7-bc1a171d431e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RYBADICECICD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RYBADICECICD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RYBADICECICD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/nodejs-microservices
          dockerfilePath: packages/dice-api/Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: aquariumkc-h5hqd7gsfwdnf4c5.azurecr.io
          registryUsername: ${{ secrets.RYBAGATEWAYCICD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RYBAGATEWAYCICD_REGISTRY_PASSWORD }}
          containerAppName: ryba-dice-cicd
          resourceGroup: fishy-group
          imageToBuild: aquariumkc-h5hqd7gsfwdnf4c5.azurecr.io/ryba-dice-cicd:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


